Remove redundant Git safe directory and add error handling for CD playbook

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -13,11 +13,7 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Set Git safe directory
-        run: git config --global --add safe.directory /__w/iac/iac
       
-
       - name: Fetch all history for git diff
         run: git fetch --depth=2
 
@@ -177,5 +173,7 @@ jobs:
         run: |
           ansible-playbook -i ansible/hosts.ini ./ansible/playbooks/deploy-docker.yml \
             --extra-vars "target_host=${{ env.target_host }} folder=${{ env.folder }} bw_access_token=${{ secrets.BW_ACCESS_TOKEN }}" | tee ansible_output.txt
-
-
+          if grep -q 'unreachable=1\|failed=[1-9]' ansible_output.txt; then
+            echo "Ansible reported failures or unreachable hosts."
+            exit 1
+          fi
